// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asmsfekobzpqrxuhbrgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzbXNmZWtvYnpwcXJ4dWhicmdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MDEzNjYsImV4cCI6MjA1NzE3NzM2Nn0.hzkqWOM9iCkgOP8GxIhChpsMQWE1JuKkrG82NJKOXUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);